### ISSUE TITLE
TGA Lemmings crashes when music starts

### ISSUE THREAD

**Issue by famiclone6502** [MiSTer-devel/PCXT_MiSTer#49] opened 2022-10-27 13:24 UTC
When starting a level on the TGA version of Lemmings (TGALEMMI.EXE), it does make sounds as the door opens, but as the first lemming drops and starts to play music, it hangs. I've tested with the latest version from 10/27. You must set it to Adlib invisible, otherwise it will detect and use it instead of Tandy music. 

I've tested a number of configurations and they all hang at that same point. I'm using the same files as I do on my real Tandy, which does play properly.

**Comment by famiclone6502** [comment] 2022-10-27 15:42
Can you share your other menu settings? I will match your setup and try again.

**Comment by spark2k06** [comment] 2022-10-30 05:20
I downloaded two lemmings versions of the TDL file and I can't reproduce it... Is it possible that you downloaded it corrupted? Without further proof, I must close this issue...

![image](https://user-images.githubusercontent.com/3509674/198863781-9fb2a631-25bb-4922-a9a5-598ee7c94659.png)

**Comment by spark2k06** [comment] 2022-11-01 05:40
Apparently, the bug only occurs in the version "Lemmings (1991)(Psygnosis Limited)[Strategy, Action].zip".

To play it, you need to hide the Adlib soundcard in the OSD menu and use this version of the game. So, what happens is that it crashes when using Tandy sound, but only with this version.

I'm marking it as a bug, the bug could be related to the use of floating point, the same reason why Landmark System Speed Test version 6.0 was recently found not to work:

https://github.com/MiSTer-devel/PCXT_MiSTer/issues/26

**Comment by spark2k06** [comment] 2022-11-28 05:04
From the tests I have been able to do, everything seems to indicate that the problem is in the Tandy ROM that uses the core, 1.01.00... ROM that in any case we can't replace, as the other versions are not compatible with the core.

The fact that there is a later version of Lemmings for Tandy that works fine, suggests that it was made to correct this problem, among others possibly.

I therefore close the subject.

**Closed by spark2k06** 2022-11-28 05:04 UTC
Labels: bug
